### ISSUE TITLE
RFC: Grape / client error handling

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/grenache#12]
**Current behaviour:**

Right now, when communicating with Grape and an error is happening in the DHT, the response is a HTTP 200 with a string, example: `302 sequence number less than current`.

That makes detecting error very hard and take a lot of performance, as every receiver must parse the data for error message. I don't think this is possible in a reliable way.

In practice, for the `grenache-nodejs-link` that looks like that right now:

```js
link.put({ v: 'hello' }, {}, (err, hash) => {
  console.log(err) // null
  console.log(hash) // 302 sequence number less than current
})
```

**Expected:**

```js
link.put({ v: 'hello' }, {}, (err, hash) => {
  console.log(err) // Error Object with message: 302 sequence number less than current and code 302
  console.log(hash) // undefined
})
```

**Proposal:**

In case of error codes, Grape should pass them to the client together with the message.

```diff
diff --git a/lib/Grape.js b/lib/Grape.js
index 7112b76..434f443 100644
--- a/lib/Grape.js
+++ b/lib/Grape.js
@@ -311,6 +311,10 @@ class Grape extends Events {
       const data = msg.data

       this.onRequest(type, data, (err, res) => {
+        if (err && err.code) {
+          rep.statusCode = err.code
+        }
+
         rep.end(JSON.stringify(err ? err.message : res))
       })
     }
```

Then clients can handle the status code, example from [grenache-nodejs-link](https://github.com/bitfinexcom/grenache-nodejs-link/blob/master/index.js#L34):

```diff
diff --git a/index.js b/index.js
index ce2bb01..57604b9 100644
--- a/index.js
+++ b/index.js
@@ -36,7 +36,16 @@ class Link extends Events {
       url: url,
       json: true,
       body: data
-    }, opts), cb)
+    }, opts), (err, res, data) => {
+
+      if (!/^2..$/.test(res.statusCode)) {
+        const err = new Error(data)
+        err.code = res.statusCode
+        return cb(err)
+      }
+
+      cb(err, data)
+    })
   }

   getRequestHash (type, payload) {
```

**Result:**

```js
link.put({ v: 'hello' }, {}, (err, hash) => {
  console.log(err) // Error Object with message: 302 sequence number less than current and code 302
  console.log(hash) // undefined
})
```

**Questions:**

 - do people depend on this right now (DHT errors are just strings and no error objects)?

**Comment by prdn** [comment]
I agree with the expected behaviour.
Please go ahead with the change

**Comment by robertkowalski** [comment]
fixed!
